---
development:
  SECRET_TOKEN: !binary |-
    OGU3YzY5MGY2NjE3MjdhMTNhNmIzZmJhNDdmMTA3YmMyM2JjYjYwM2E0NjVl
    NDgzMzkyOGUxNDVmM2Iy
  TWITTER_CONSUMER_KEY: LefQzTdK10MH5bp9XY0pkg
  TWITTER_CONSUMER_SECRET: okbZO6Mgx9DCzcn8xOkydPkctfCyPyis0VBhHMBMgJo
test:
  SECRET_TOKEN: !binary |-
    OGU3YzY5MGY2NjE3MjdhMTNhNmIzZmJhNDdmMTA3YmMyM2JjYjYwM2E0NjVl
    NDgzMzkyOGUxNDVmM2Iy
  TWITTER_CONSUMER_KEY: LefQzTdK10MH5bp9XY0pkg
  TWITTER_CONSUMER_SECRET: okbZO6Mgx9DCzcn8xOkydPkctfCyPyis0VBhHMBMgJo
  LIVE_URL: http://example.com/v1/live.json
